// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvTH3LhZHayzYZhigJUICuaAUdSOAZtDQ',
    appId: '1:141784513375:web:b6880dcec484526c2dd4ea',
    messagingSenderId: '141784513375',
    projectId: 'fashion-store-de-2026',
    authDomain: 'fashion-store-de-2026.firebaseapp.com',
    storageBucket: 'fashion-store-de-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAElSL_8Sreb1avOyVe5cy4W1HV7GWnB50',
    appId: '1:141784513375:android:98321829ef40e0892dd4ea',
    messagingSenderId: '141784513375',
    projectId: 'fashion-store-de-2026',
    storageBucket: 'fashion-store-de-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfrYnWReYD4BdOMmXUQ1GMvwg8WVU7wk',
    appId: '1:141784513375:ios:893c796c644118f72dd4ea',
    messagingSenderId: '141784513375',
    projectId: 'fashion-store-de-2026',
    storageBucket: 'fashion-store-de-2026.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfrYnWReYD4BdOMmXUQ1GMvwg8WVU7wk',
    appId: '1:141784513375:ios:893c796c644118f72dd4ea',
    messagingSenderId: '141784513375',
    projectId: 'fashion-store-de-2026',
    storageBucket: 'fashion-store-de-2026.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvTH3LhZHayzYZhigJUICuaAUdSOAZtDQ',
    appId: '1:141784513375:web:4a4eff9852d7ec832dd4ea',
    messagingSenderId: '141784513375',
    projectId: 'fashion-store-de-2026',
    authDomain: 'fashion-store-de-2026.firebaseapp.com',
    storageBucket: 'fashion-store-de-2026.firebasestorage.app',
  );
}
